import Head from 'next/head';
import localFont from 'next/font/local';
import styles from '@/styles/Home.module.scss';
import FocusWall from '@/components/FocusWall';
import MainPage from '@/components/MainPage';
import Footer from '@/components/Footer';
import Carousel from '@/components/Carousel';
import WallConstruct from '@/components/WallConstruct';
import Cubes from '@/components/Cubes';
import CubesConstruct from '@/components/CubesConstruct';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <MainPage />
        <FocusWall />
        <WallConstruct />
        <Cubes />
        <CubesConstruct />
        <Carousel />
        <Footer />
      </div>
    </>
  );
}
